name: deploy
on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * *' # Everyday at 12am
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

 
      - name: Restart Node Server
        uses: appleboy/ssh-action@master
        with:
          host: scrbsmqdk007497
          username: pkh045
          password: yc]%2z\93C(cB[WE
          port: 22
          script: |
            cd /home/pkh045
			mkdir test
            git fetch origin master
