name: testfiles
on:
  pull_request:
    branches:
      - main
    paths-ignore:

jobs:
  kafkacluster-api:
    runs-on: ubuntu-20.04
    name: validation
    steps:

          run: |
            mkdir -p /tmp/test
            SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
            ssh -i $SSH_PRIVATE_KEY root@scrbsmqdk007497
