---
name: CI_SSHs
on:
  push:
    branches:
      - main
    paths-ignore:
      - ""
jobs:
  run_tests:
    runs-on:
    - self-hosted
    - activemq_7491
    - ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run script file
        run: chmod +x ./.github/script.sh
             ./.github/script.sh
        shell: bash
