---
name: CI_SSH
on:
  push:
    branches:
      - main
    paths-ignore:
      - ""
jobs:
  example-job:
    steps:
      - name: Run build script
        run: ./.github/script.sh
        shell: bash
