---
name: CI_SSH
on:
  push:
    branches:
      - main
    paths-ignore:
      - ""
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          chmod +x ./.github/script.sh
          ./Github_Actions/.github/script.sh
